_target_: agent.idm_agent.IDM_Agent
_recursive_: false

device: ${device}

### same as idm_latent_policy.yaml
latent_policy:
  _target_: agent.idm_latent_policy.IDM_Latent_Policy_Agent
  _recursive_: false


  device: ${device}

  model:
    _target_: agent.idm_latent_policy.IDM_Latent_Policy
    _recursive_: false

    visual_input: True
    device: ${device}

    input_dim: 7

    diffusion_opt:
      beta_max: 0.3
      interval: 50
      device: ${device}
      ema: 0.9

    obs_encoder:
      _target_: agent.obs_encoder.ImageEncoder
      embedding_dim: 256

  trainset:
  valset:

  optimization:
    _target_: torch.optim.AdamW
    lr: 1e-4
    weight_decay: 0

  train_batch_size: 64
  val_batch_size: 64
  num_workers: 2
  epoch: 500
  eval_every_n_epochs: 10



###load action decoder
idm_model:
  _target_: agent.idm_baseline.IDM_Baseline_Agent
  _recursive_: false

  model:
    _target_: agent.idm_baseline.IDM_Baseline
    _recursive_: false
    device: ${device}
    model:
      _target_: agents.models.idm.idm_model.BaselineModel
      input_dim: ${obs_dim}
      hidden_dims: ${hidden_dims}
      action_dim: ${action_dim}
      backbone: ${backbone}
      mask_dim: ${obs_mask_dim}

  trainset:
  valset:

  optimization:
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 0.01

  train_batch_size: ${train_batch_size}
  val_batch_size: ${val_batch_size}
  num_workers: ${num_workers}
  epoch: ${epoch}
  device: ${device}
  scale_data: False
  eval_every_n_epochs: ${eval_every_n_epochs}

