_target_: agent.idm_baseline.IDM_Baseline_Agent
_recursive_: false

model:
  _target_: agent.idm_baseline.IDM_Baseline
  _recursive_: false
  device: ${device}
  model:
    _target_: agents.models.idm.idm_model.BaselineModel
    input_dim: ${obs_dim}
    hidden_dims: ${hidden_dims}
    action_dim: ${action_dim}
    backbone: ${backbone}
    mask_dim: ${obs_mask_dim}

trainset:
  _target_: spoon_dataset.MergedDataset
  dataset_path_A: ${train_dataset_path_A}
  dataset_path_B: ${train_dataset_path_B}
  img_data: False
  normalization: True

valset:
  _target_: spoon_dataset.MergedDataset
  dataset_path_A: ${test_dataset_path_A}
  dataset_path_B: ${test_dataset_path_B}
  img_data: False
  normalization: False

optimization:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 0.01

train_batch_size: ${train_batch_size}
val_batch_size: ${val_batch_size}
num_workers: ${num_workers}
epoch: ${epoch}
device: ${device}
scale_data: False
#scale_set: ${scale_set}
eval_every_n_epochs: ${eval_every_n_epochs}